pr:
- main  # Trigger pipeline on PR targeting main branch

pool:
  vmImage: ubuntu-latest

variables:
  # Paths
  backendPath: 'src/backend/Manu.AiAssistant/Manu.AiAssistant.WebApi'
  frontendPath: 'src/frontend'

  # Docker image names
  backendImageName: 'manu-assistant-app-backend'
  frontendImageName: 'manu-assistant-app-frontend'

  # Unique tag for PR builds
  imageTag: 'PR-$(System.PullRequest.PullRequestId)-$(Build.BuildNumber)'

jobs:
# -------------------------------
# Build backend Docker image (no push)
# -------------------------------
- job: BackendDockerBuild
  displayName: 'Build Backend Docker (PR)'
  steps:
  - task: Docker@2
    displayName: 'Build backend image'
    inputs:
      command: 'build'
      repository: '$(backendImageName)'
      Dockerfile: '$(Build.SourcesDirectory)/$(backendPath)/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/$(backendPath)'
      tags: |
        $(imageTag)
      arguments: '--platform linux/amd64'

# -------------------------------
# Build frontend Docker image (no push)
# -------------------------------
- job: FrontendDockerBuild
  displayName: 'Build Frontend Docker (PR)'
  steps:
  - task: Docker@2
    displayName: 'Build frontend image'
    inputs:
      command: 'build'
      repository: '$(frontendImageName)'
      Dockerfile: '$(Build.SourcesDirectory)/$(frontendPath)/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/$(frontendPath)'
      tags: |
        $(imageTag)
      arguments: '--platform linux/amd64'
