trigger: none

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  backendPath: 'src/backend/Manu.AiAssistant/Manu.AiAssistant.WebApi'
  frontendPath: 'src/frontend'
  backendImageName: 'manu-assistant-app-backend'
  frontendImageName: 'manu-assistant-app-frontend'
  dockerPlatform: 'linux/amd64'

jobs:
- job: BackendDockerBuild
  displayName: 'Build Backend Docker (PR)'
  timeoutInMinutes: 15
  steps:
  - task: Cache@2
    displayName: 'Cache .NET packages'
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
      path: ~/.nuget/packages
      restoreKeys: |
        nuget | "$(Agent.OS)"
  - task: DockerInstaller@0
    displayName: 'Ensure Docker Buildx is installed'

  - script: |
      docker buildx create --use || true
      docker buildx build \
        --file "$(Build.SourcesDirectory)/$(backendPath)/Dockerfile" \
        --build-arg BUILD_CONFIGURATION=Release \
        --platform $(dockerPlatform) \
        --cache-from type=gha \
        --cache-to type=gha,mode=max \
        -t $(backendImageName):pr-$(System.PullRequest.PullRequestId)-$(Build.BuildNumber) \
        $(Build.SourcesDirectory)/$(backendPath)
    displayName: 'Build backend image (with cache)'
    env:
      DOCKER_BUILDKIT: 1

- job: FrontendDockerBuild
  displayName: 'Build Frontend Docker (PR)'
  timeoutInMinutes: 15
  steps:
  - task: Cache@2
    displayName: 'Cache npm dependencies'
    inputs:
      key: 'npm | "$(Agent.OS)" | frontend-$(Build.SourcesDirectory)/src/frontend/package-lock.json'
      path: '$(Build.SourcesDirectory)/src/frontend/node_modules'
      restoreKeys: |
        npm | "$(Agent.OS)"

  - task: DockerInstaller@0
    displayName: 'Ensure Docker Buildx is installed'

  - script: |
      cd "$(Build.SourcesDirectory)/src/frontend"
      docker buildx create --use || true
      docker buildx build \
        --file Dockerfile \
        --platform $(dockerPlatform) \
        --cache-from type=gha \
        --cache-to type=gha,mode=max \
        -t $(frontendImageName):pr-$(System.PullRequest.PullRequestId)-$(Build.BuildNumber) \
        .
    displayName: 'Build frontend image (with cache)'
    env:
      DOCKER_BUILDKIT: 1
