# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: ls -R $(Build.SourcesDirectory)
  displayName: 'List files in folder'
- script: ls -R $(Build.SourcesDirectory)/src
  displayName: 'List files in src folder'
- script: dotnet restore $(Build.SourcesDirectory)/src/backend/Manu.AiAssistant/Manu.AiAssistant.sln
  displayName: 'Restore dependencies'
- script: dotnet build $(Build.SourcesDirectory)/src/backend/Manu.AiAssistant/Manu.AiAssistant.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop-backend'

