trigger: none

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  backendPath: 'src/backend/Manu.AiAssistant/Manu.AiAssistant.WebApi'
  frontendPath: 'src/frontend'
  backendImageName: 'manu-assistant-app-backend'
  frontendImageName: 'manu-assistant-app-frontend'

jobs:
- job: BackendDockerBuild
  displayName: 'Build Backend Docker (PR)'
  steps:
  - task: Docker@2
    displayName: 'Build backend image'
    inputs:
      command: 'build'
      repository: '$(backendImageName)'
      Dockerfile: '$(Build.SourcesDirectory)/$(backendPath)/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/$(backendPath)'
      tags: |
        pr-$(System.PullRequest.PullRequestId)-$(Build.BuildNumber)
      arguments: '--platform linux/amd64'

- job: FrontendDockerBuild
  displayName: 'Build Frontend Docker (PR)'
  steps:
  - task: Docker@2
    displayName: 'Build frontend image'
    inputs:
      command: 'build'
      repository: '$(frontendImageName)'
      Dockerfile: '$(Build.SourcesDirectory)/$(frontendPath)/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/$(frontendPath)'
      tags: |
        pr-$(System.PullRequest.PullRequestId)-$(Build.BuildNumber)
      arguments: '--platform linux/amd64'
