trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # General
  azureServiceConnection: 'azure-service-connection'  # ARM service connection
  acrName: 'manucode-ecfccsaghrewfwb7'               # ACR name
  imageTag: '$(Build.BuildId)-$(Build.SourceBranchName)'  # unique per build + branch

  # Paths
  backendPath: 'src/backend/Manu.AiAssistant'
  frontendPath: 'src/frontend'

  # Docker image names
  backendImageName: 'manu-assistant-app-backend'
  frontendImageName: 'manu-assistant-app-frontend'

jobs:
# -------------------------------
# Build & push backend Docker image
# -------------------------------
- job: BackendDocker
  displayName: 'Build & Push Backend Docker'
  steps:
  - task: Docker@2
    displayName: 'Build and push backend image'
    inputs:
      containerRegistry: '$(azureServiceConnection)'
      repository: '$(backendImageName)'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/$(backendPath)/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/$(backendPath)'
      tags: |
        $(imageTag)
      arguments: '--platform linux/amd64'

# -------------------------------
# Build & push frontend Docker image
# -------------------------------
- job: FrontendDocker
  displayName: 'Build & Push Frontend Docker'
  dependsOn: []
  steps:
  - task: Docker@2
    displayName: 'Build and push frontend image'
    inputs:
      containerRegistry: '$(azureServiceConnection)'
      repository: '$(frontendImageName)'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/$(frontendPath)/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/$(frontendPath)'
      tags: |
        $(imageTag)
      arguments: '--platform linux/amd64'
