# deploy-test.yml
trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: manu-assistant-build-main
      trigger: none

stages:
  - stage: TestArtifacts
    displayName: "Test Artifact Paths"
    jobs:
      - job: ListArtifacts
        displayName: "List Artifacts Folder Content"
        steps:

          # -------------------------------
          # Download build artifacts
          # -------------------------------
          - download: buildPipeline
            displayName: "Download buildPipeline artifacts"

          # -------------------------------
          # List folders in pipeline workspace
          # -------------------------------
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-service-connection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Pipeline workspace: $(Pipeline.Workspace)"
                echo "Listing workspace:"
                ls -la $(Pipeline.Workspace)

                echo "Listing backend-image-metadata folder:"
                ls -la $(Pipeline.Workspace)/**/backend-image-metadata || echo "No backend-image-metadata found"

                echo "Listing frontend-image-metadata folder:"
                ls -la $(Pipeline.Workspace)/**/frontend-image-metadata || echo "No frontend-image-metadata found"
            displayName: "List Artifacts Contents"
